development:
  adapter: postgresql
  database: urlshortener_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: urlshortener_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: urlshortener_production
  pool: 5
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] %>
  


